In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

In [3]:
data = pd.read_csv("../data/nba_player_bio.csv", index_col=0)

data.head()

,PLAYER,TEAM,AGE,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT YEAR,DRAFT ROUND,DRAFT NUMBER,...,PTS,REB,AST,NETRTG,OREB%,DREB%,USG%,TS%,AST%,season
0,A.C. Green,DAL,33.0,6-9,225.0,Oregon State,USA,1985,1,23,...,7.2,7.9,0.8,-7.4,8.9,18.4,11.8,52.3,4.5,1996-97
1,Aaron McKie,DET,24.0,6-5,209.0,Temple,USA,1994,1,17,...,5.2,2.7,1.9,3.7,2.6,11.3,14.2,52.4,16.3,1996-97
2,Aaron Williams,VAN,25.0,6-9,225.0,Xavier,USA,Undrafted,Undrafted,Undrafted,...,6.2,4.3,0.5,-9.3,11.3,14.4,16.1,59.9,5.1,1996-97
3,Acie Earl,MIL,27.0,6-11,240.0,Iowa,USA,1993,1,19,...,4.0,2.0,0.4,-6.4,6.7,12.2,22.0,43.5,7.7,1996-97
4,Adam Keefe,UTA,27.0,6-9,241.0,Stanford,USA,1992,1,10,...,3.8,3.5,0.5,7.2,9.6,15.8,12.4,57.2,5.1,1996-97